apiVersion: v1
kind: Service
metadata:
  name: maintenance-manager-service
spec:
  selector:
    app: maintenance-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
