version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: maintenancemanager-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4444
      POSTGRES_DB: MaintenanceManager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - maintenancenet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MaintenanceManager"]
      interval: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: MaintenanceManager.Web.Service/Dockerfile
    container_name: maintenancemanager-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=MaintenanceManager;Username=postgres;Password=4444"
    ports:
      - "8080:8080"
    networks:
      - maintenancenet
     
volumes:
  postgres_data:

networks:
  maintenancenet:
